services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    container_name: postgres_db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: unless-stopped
    container_name: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

volumes:
  pgdata:
