export enum TokenType {
  ADMIN_TRANSFER = 'ADMIN_TRANSFER',
  ACCESS = 'ACCESS',
  REFRESH = 'REFRESH',
  PASSWORD_RESET = 'PASSWORD_RESET',
  CURRENT_USER_PASSWORD_RESET = 'CURRENT_USER_PASSWORD_RESET',
  REGISTRATION = 'REGISTRATION',
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
}
